src/main/errors.js, src/main/minio.js, src/test/unit/test.js
- Rename setUserAgent as setAppInfo(appName, appVersion).
No other comments can be added by the application.
- Fixes all the tests as well.
Fixes #351
=> userAgent: Standardize userAgent with the new style.

.travis.yml, API.md, README.md, examples/bucket-exists.js, examples/fget-object.js, examples/fput-object.js, examples/get-bucket-acl.js, examples/get-object.js, examples/get-partialobject.js, examples/list-buckets.js, examples/list-incomplete-uploads.js, examples/list-objects.js, examples/make-bucket.js, examples/presigned-getobject.js, examples/presigned-postpolicy.js, examples/presigned-putobject.js, examples/put-object.js, examples/remove-bucket.js, examples/remove-incomplete-upload.js, examples/remove-object.js, examples/set-bucket-acl.js, examples/stat-object.js, src/main/errors.js, src/main/helpers.js, src/main/minio.js, src/main/signing.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Add a new field 'transport' to params and avoid taking new arguments
for Client constructor.
=> arguments: Take arguments like other libraries and validate them.

src/main/helpers.js, src/main/minio.js, src/main/s3-endpoints.js, src/test/functional/functional-tests.js
This patch essentially solves two problems
- accessing bucket names right after they were created. In current style
if we try to access the buckets we would get 'Access Denied'.
This can be solved by sending the requests directly to the endpoint
where the bucket was created. For this we have to automatically use
the relevant endpoint based on bucket location, similar to how it is
achieved in 'aws-sdks'.
- bucket names with '.' cannot be used with virtual host style for
HTTPS requests due to SSL certificate issue, so in this case we fallback
to using path style instead for such requests, similar to how it is achieved
in 'aws-sdks'.
=> getRequestOptions: Constructs now host based on region and bucketName.

README.md, examples/presigned-postpolicy.js, src/main/minio.js, src/test/functional/functional-tests.js
The reason to do this is because bucket names can be in
various different regions and for users it becomes convenient
if we return back the proper endpoint which can be safely used
without worrying about virtual host style or path style.
We have enough information to provide a proper URL, this is also
consistent with other Presigned operations as it would be an
expected behavior.
=> api: change presignedPostPolicy to return back proper URL.

API.md, README.md
So I changed documentation to reflect port as a number.
=> Port in documentation is a string, where client expects a number.

src/main/minio.js
Previously when you try to `fGetObject` which does not exist on the server  the app crashed with:
```
TypeError: old path must be a string at TypeError (native)
at Object.fs.rename (fs.js:673:11)
at rename (/source/minio.js:675:10)
```
This was caused by the fact that the `partFile` stays `null` if the download fails, then `fs` fails to rename the file.
=> * Fixed error on downloading non-existing resourse

src/main/helpers.js
@harshavardhana see if this is ok:
```
-  // AWS percent-encodes some extra non-standard characters in a URI
-  output = output.replace(/[*]/g, function(ch) {
-    return '%' + ch.charCodeAt(0).toString(16).toUpperCase()
-  
})
```
i could not find this in minio-go so removed it.
=> Use encodeURIComponent directly and remove unneeded code.

src/main/minio.js, src/test/unit/test.js
Previous to this commit, `presignedPutObject` would actually throw a
TypeError if you don't put in an expiry, unlike `presignedGetObject`.
However, the documentation on the expiry stated that it is optional and
defaults to 7 days. This fixes that and adds a test.
=> make `presignedPutObject` expiry actually optional

.travis.yml, appveyor.yml
Before this, for reasons unknown, the CIs wouldn't run the unit tests,
they would only run the linters. To make life easier on the maintainers,
run the unit tests for each PR.
=> ci: run unit tests

docs/API.md, examples/get-bucket-policy.js, examples/set-bucket-policy.js, package.json, src/main/bucket-policy.js, src/main/errors.js, src/main/minio.js, src/main/transformers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
This commit adds two new functions, `getBucketPolicy` and
`setBucketPolicy`, both of which allow the user to manage bucket policy
via the node client. Documentation, examples, tests are included.
=> add `getBucketPolicy` and `setBucketPolicy`

docs/API.md, examples/minio/listen-bucket-notification.js, package.json, src/main/minio.js, src/main/notification.js, src/main/transformers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
This commit adds `listenBucketNotification`, a method that will
automatically poll s3 for updates on a specific bucket config. This also
adds examples and documentation, although the tests are lacking.
Functional tests were not added because `listenBucketNotification` doesn't work on Amazon.
=> add `listenBucketNotification`

docs/API.md, src/main/minio.js, src/main/object-uploader.js, src/main/transformers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
This PR adds a new stream uploader, `.streamObject()`, which allows for easy uploading of a stream to s3.
This also ports `.fPutObject()` and `.putObject()` to use `.streamObject()` under the hood.
**NOTE**: this contains a breaking change. Before this, uploading a stream of size 1GB (for example) but declaring it as 2GB would leave the multipart upload open on the server. This PR now makes it close the multipart upload once the stream ends. The tests have been updated/removed for that.
=> add new stream uploader

src/main/minio.js
Replace #534
Partial fix for #535, a request stream will work most of the time but is this stream is also 'keep-alive' the library still not handle the problem and won't free the connection
=> Do not modify global http(s) agent, instead construct an agent per transport.

src/main/helpers.js
```
krishna@escape:~/dev$ cat fput-object-s3.js
var Minio = require('./minio-js')
var Fs = require('fs')
// find out your s3 end point here:
// http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
var s3Client = new Minio.Client({
endPoint: 's3.amazonaws.com',
secure: false,
accessKey: 'XXXXX',
secretKey: 'XXXX'
})
s3Client.traceOn()
s3Client.fPutObject('krisupload', 'passwd', '/etc/passwd', '', function(e, etag) {
console.log(e, etag)
})
krishna@escape:~/dev$ node fput-object-s3.js
/home/krishna/dev/minio-js/dist/main/helpers.js:134
contentType = 'application/octet-stream'
^
ReferenceError: contentType is not defined
at probeContentType (/home/krishna/dev/minio-js/dist/main/helpers.js:134:16)
at Client.fPutObject (/home/krishna/dev/minio-js/dist/main/minio.js:841:21)
at …
```
=> contentType variable was not declared.

docs/API.md, src/main/minio.js, src/test/functional/functional-tests.js
Add region= option to our API constructor. This option
is added to avoid making calls to server when an
application written using `minio-js` is only meant
to generate presigned URLs which is a quite common use
case.
Setting this option - overrides any future region
changes and makes the API more stricter. For example
if you are going to use your initialized client
against a bucket which exists in a different region
all API operations would fail.
=> Allow bucket region cache to be overriden.

src/main/minio.js
mkdirp works fine with '.'
Fixes #549
=> No need to handle '.' as a special case.

package.json
When running tests using `minio-js` with Jest and jsdom it was throwing errors due to minio-js using an old version of `source-map-support`.
```
/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486
throw new DOMException(DOMException.SYNTAX_ERR);
^
SyntaxError
at XMLHttpRequest.open (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486:15)
at retrieveSourceMapURL (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:61:9)
at retrieveSourceMap (/Users/will3942/work/spotlightdata/nanowire-rubix/node_modules/minio/node_modules/source-map-support/source-map-support.js:86:26)
at mapSourcePosition …
```
=> Update source-map-support version

src/main/bucket-policy.js, src/main/minio.js
Also make error messages a bit consistent.
Fixes #573
=> api: Error exception templates should have expected variables

src/main/minio.js
'finish' event was fired before 'error' event causing removal of
error handlers and hence causing the application to crash
=> remove 'finish' handlers on request

src/test/functional/functional-tests.js
Currently EuCentral makebucket test runs if endpoint is not play server. Should instead check if it is aws endpoint
=> Run makebucket test for eu only for s3

src/test/functional/functional-tests.js
minio-js functional tests should run as standalone program, independent of the minio-js repo itself. This is the pre-condition for https://github.com/minio/mint/issues/91
=> Update minio-js functional tests to run as standalone

package.json, src/main/helpers.js, src/main/minio.js, src/main/signing.js, src/test/functional/functional-tests.js, src/test/unit/test.js
This commit removes the dependency on the MomentJS library for
performance, and instead replaces its long/short date formatting
APIs with our own native alternatives.
This also adds unit tests to make sure the date helper functions are
covered.
Fixes: #570
This commit also skips a unit test which began failing after a change in
minio server. It will skip on non-AWS hosts. See:
minio/minio@75c43bf
=> remove moment, use native implementation

docs/API.md, src/main/helpers.js, src/main/minio.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Issue: https://github.com/minio/minio-js/issues/568
This contains the basis for the new Promise-based API. Right now it makes callbacks *optional*, and when no callback is given, it will instead return a Promise. Backwards compatibility is maintained. Tests and documentation have been added.
Right now this only changes actions dealing with buckets, though it is easily scale-able once we decide this is the way to go. **Seeking feedback!**
=> Add Promise-based API

src/main/minio.js, src/test/unit/test.js
Minio-js is passing the x-amz-copy-source-if-modified-since and x-amz-copy-source-if-unmodified-since values in the wrong format to the server. Fix has been added to minio.js file to send the correct time format. The unit test also had a sample date in the wrong format, which has also been fixed.
Fixes #620
=> Fix date format in copy conditions

gulpfile.js, package.json, src/test/functional/functional-tests.js
Checked tests have been implemented 
This is more a SDK functionality.
- [x ] 26. test for copyobject() etag:condition matching negative case missing.
The test type has been changed from it to step, to support serial execution of the tests in js.
Fixes (#612)
=> Missing functional tests for minio-js

src/main/minio.js
awesome library!
i need support for `sessionToken` because i'm using `sts.assumeRole(...)` to generate temporary credentials for users, and my bucket's policy limits users by their current role session. With this change, it works for me
=> support session token

appveyor.yml, src/main/minio.js, src/main/object-uploader.js, src/main/transformers.js, src/test/functional/functional-tests.js
Do not calulate Content-MD5 for secure, non-anonymous put object
requests.
Fixes #589
=> Skip content-MD5 for secure putobject call, add prefix to bucket name in functional test

src/main/minio.js, src/main/notification.js, src/main/object-uploader.js
=> Close the socket connection if we don't read from it

docs/API.md
=> Fix typo in listObjects{v2} API

src/main/minio.js
=> Drain data from response in browserify environment

src/main/object-uploader.js
=> Support putObject to upload an empty file.

docs/API.md, examples/bucket-exists.js, package.json, src/main/minio.js, src/test/functional/functional-tests.js
This is a breaking API change. bucketExists API will require
a callback with this signature cb(err, bool). This is a better
way to indicate whether a bucket exists or not.
Fixes #648
=> bucketExists: Use a bool to indicate if a bucket exists or not

docs/zh_CN/API.md
`.key` should be `.name`.
The related Engish version PR is [Fix typo in listObjects](https://github.com/minio/minio-js/pull/660/commits/81366ebb052020d2927bfac3075f58a2f7c80b40) .
=> Fix typo in listObjects{v2} API in Chinese docs.

src/test/functional/functional-tests.js
I couldn't find a spec for this. I think it's common to have to handle this error in a specific way.
=> Adds spec for getObject on missing key

docs/API.md, src/main/minio.js
Support for setting http request options (things like http agent, TLS related configs)
=> Support for setRequestOptions

src/test/functional/functional-tests.js
If server returns non-NotImplemented for listenbucket call, we should not do PutObject and hence call done() again
=> Fix listenBucketNotification test logic

package.json
Move source-map-support to devDependencies so that this
package doesn't get instaleld in production.
Refer: https://github.com/minio/minio-js/pull/710#issuecomment-404276845
=> Move source-map-support package to devDependencies

src/main/minio.js, src/test/unit/test.js
When the Client is initialized with option `secure: false` or `secure: true`, an error should be thrown stating secure option is deprecated.
=> fix error not thrown when secure param is passed

docs/API.md, examples/list-objects-v2.js, src/main/minio.js, src/test/functional/functional-tests.js
Add parameter start-after to ListObjectsV2 to make the iteration uninterruptible. 
Resolves the [issue](https://github.com/minio/minio-js/issues/733)
=> Add parameter start-after to ListObjectsV2

.travis.yml, docs/API.md, examples/presigned-getobject-request-date.js, src/main/helpers.js, src/main/minio.js, src/test/functional/functional-tests.js
Hi there,
I just added a parameter `requestDate` to the methods `presignedUrl()` and `presignedGetObject()`.
Please have a look at #724 for more details.
My todo checklist:
=> Add requestDate parameter to presignedUrl() and presignedGetObject()

src/test/functional/functional-tests.js
Metadata length check will fail if auto encryption is turned on,
as auto encryption adds extra metadata.
=> Removing metadata length check

README.md, README_zh_CN.md, docs/API.md, docs/zh_CN/API.md
Link to shopping app example was broken.  It was pointing to a non-existent link in docs.minio.io. Pointed it to it's repo in github.
Fixes #755
=> Fix broken link to the shopping app example

src/test/functional/functional-tests.js
As it was before the following happened
1. call putObject with the 5mb file. In reality a multipart upload is performed with the file as the only part
2. Create a part file using the object name and the md5 hash and put in 100kb of random data
3. Call fGetObject. fGetObject will look for a part file containing the object name and the etag, since a multipart upload was performed, the etag will not match the md5 for aws (prob minio as well).
4. Test passes as the md5 hash matches for the the uploaded and the downloaded file
With the PR we instead call statobject and use the etag we get to create the part file. Also the part file will contain the first 100kb from the 5mb file, instead of 100kb of random data. The fGetObject will then use the part file, and skip those bytes in the part file, …
=> fGetobject-resume test is not testing resume

examples/fput-object.js, src/main/helpers.js, src/main/minio.js, src/test/functional/functional-tests.js
This commit also corrects the fput-object.js example and adds functional
tests to check if this feature is working correctly
Fixes #763
=>  Make fPutObject automatically detect content-type

src/test/functional/functional-tests.js
Related: https://github.com/minio/minio-js/issues/766
=>  Change content-language to a valid ISO 639-1 language code in functional tests

docs/API.md, docs/zh_CN/API.md, examples/set-bucket-notification.js
MinIO doesn't support `TopicConfig`, but supports `QueueConfig`. Changing the example to use `QueueConfig` instead of `TopicConfig`, which works only on `AWS S3`
Fixes #775
=> Example: Use QueueConfig instead of TopicConfig

.travis.yml, appveyor.yml
Due to 'npm prepublish' being deprecated, the relevant command was moved
to 'npm prepublishOnly', which doesn't run on local 'npm install' and
resulted in our tests not being ran on Appveyor. The functionality of
'npm prepublish' is preserved on 'npm prepare', but that is already
reserved for users who install the package directly from the GitHub URL.
Similarly, there were changes made to the package.json file that caused
tests to not being run on Travis as well. Therefore, an additional line
has been added to both appveyor.yml and travis.yml to run the tests.
=> Ensure that tests are run on CI Platforms

src/main/helpers.js, src/main/minio.js
Consider the following code:
```javascript
const metadata = {
some: 'thing',
};
for (const file of files) {
client.fPutObject(bucketName, objectName, file, metadata, callback);
}
```
The problem with this code is that it mutates the metadata object. After the first iteration the object contains the 'content-type' property. What follows is the wrong 'content-type' being set on the remaining files. 
I solved the problem by creating a new object instead of mutating the original one.
=> Fix: avoid metadata mutation in fPutObject

src/main/object-uploader.js, src/test/functional/functional-tests.js
- Socket were not released by each uploaded part http request.
- When using http agent with keepalive, each request were still referenced through sockets and indirectly reference chunk data.
=> Fix multipart upload with keepalive memory leak

docs/API.md
Since `bucketExists` was [promisified](https://github.com/minio/minio-js/blob/518e5a8815dd579f3fcd2d2a4f4cb2599ad3d580/src/main/minio.js#L2115), it should be reflected in the API document.
=> Update bucketExists in API.md

src/main/xml-parsers.js
userMetaData returned when ListObjectsV2Metadata is null in the case of Azure Gateway. Adding a null check before accessing an index in userMetadata
=> ListObjectsV2Metadata: userMetadata null check

package.json, src/main/minio.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js
Fixes #859 
This PR replaces the old xml parser package, `xml2js`, with the much faster, `fast-xml-parser`. package.
=> Replaces the old xml parser with a new, faster one

src/main/xml-parsers.js
Fixes #886 
Added the forgotten `toArray` conversion for parsed `Content` element.
=> Adds the missing toArray conversion to parsed listObject Content

src/main/helpers.js
Fixes #878 
With this fix, dot character, `.`, at the end of a domain name becomes a valid character.
=> Allows dot character, '.', at the end of a domain name

docs/API.md, examples/list-objects.js, src/main/minio.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js
Version Id support in listObjects API
=> VersionId support in listObjects API

docs/API.md, examples/remove-objects.js, src/main/minio.js, src/test/functional/functional-tests.js
VersionId Support in removeObjects api
=> VersionId Support in removeObjects api

src/main/minio.js
Fixes #898 
Adds the missing `x-amz-security-token` into the formData, returned from presignedPostPolicy.
=> Adds x-amz-security-token into the formData

README.md, docs/API.md, examples/get-object-lock-config.js, examples/reset-object-lock-config.js, examples/set-object-lock-config.js, src/main/helpers.js, src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Get/Set Object locking
- `makeBucket(bucketName, region[, makeOpts , callback])`
- `setObjectLockConfig(bucketName, lockConfig [, callback])`
- `getObjectLockConfig(bucketName [, callback])`
=> Get/Set Object lock config APIs

README.md, docs/API.md, examples/get-object-retention.js, examples/put-object-retention.js, examples/remove-object.js, src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Object retention APIs.
Note: this depends on #919 
<summary> Test Script </summary>
<details>
var Minio = require("../../dist/main/minio")
endPoint:"127.0.0.1",
port:9000,
useSSL:false,
accessKey:"minio",
secretKey :"minio123"
})
const file = '/home/prakash/Downloads/HouseDesign/E00000000833.jpg'
function makeBucketWithObjectLock (buckName,makeOpts,cb){
const bucketTaggingPromise = minioClient.makeBucket(buckName,makeOpts)
bucketTaggingPromise.then(() => {
console.log("makeBucketWithObjectLock success...")
cb && cb()
})
.catch((e)=>{
console.log("makeBucketWithObjectLock Error",e)
})
}
function setObjectLockConfig (buckName,lockOpts,cb){
const bucketTaggingPromise = minioClient.setObjectLockConfig(buckName,lockOpts)
bucketTaggingPromise.then(() => { …
=> Object retention put/get APIs

README.md, docs/API.md, examples/get-bucket-tagging.js, examples/get-object-tagging.js, examples/put-object-tagging.js, examples/remove-bucket-tagging.js, examples/remove-object-tagging.js, examples/set-bucket-tagging.js, examples/set-object-tagging.js, src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Implement Tags on 
- Bucket
- `setBucketTagging`
- `removeBucketTagging`
- `getBucketTagging`
- Object
- `setObjectTagging`   ( Supports optional versionId)
-  `removeObjectTagging` (Supports optional versionId)
- `getObjectTagging` (Supports optional versionId)
Closes #884
=> Bucket/Object Tags feature with versioning support included

src/main/signing.js
The sessionToken (at least in AWS) is base64 encoded and may contain forward slashes, plusses etc. Without escaping it you get invalid token responses when generating pre-signed gets.
=> Fixed sessionToken not being escaped in the query

README.md, docs/API.md, examples/get-bucket-replication.js, examples/remove-bucket-replication.js, examples/set-bucket-replication.js, src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Bucket replication set, get, remove APIs.
`setBucketReplication(bucketName, replicationConfig={}, cb)`
`getBucketReplication(bucketName, cb)`
`removeBucketReplication(bucketName, cb)`
Test Script:
[test-replication.txt](https://github.com/minio/minio-js/files/6544790/test-replication.txt)
**Note:** `arn` has to be generated manually and fed to the script to test. Steps are commented in the test script.
Place it inside of `src/test` and then `npm run compile` and then `node src/test/test-replication.js`  
Note:
To run all functional tests locally the below must be exported and certificates as required:
`
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373;export MINIO_KMS_KES_KEY_FILE=root.key;export MINIO_KMS_KES_CERT_FILE=root.cert;export MINIO_KMS_KES_KEY_NAME=my-minio-key;
`
=> Bucket replication config set, get, remove

README.md, docs/API.md, examples/get-object-legal-hold.js, examples/set-object-legal-hold.js, src/main/helpers.js, src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js, src/test/unit/test.js
Legal hold APIs support
`getObjectLegalHold(bucketName, objectName, getOpts={}, cb)`
`setObjectLegalHold(bucketName, objectName, setOpts={}, cb)`
Note:
To run all functional tests locally the below must be exported and certificates as required:
`
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373;export MINIO_KMS_KES_KEY_FILE=root.key;export MINIO_KMS_KES_CERT_FILE=root.cert;export MINIO_KMS_KES_KEY_NAME=my-minio-key;
`
=> Get/set legal hold APIs

src/main/object-uploader.js, src/test/functional/functional-tests.js
With current `minio@7.0.18` when uploading a large file from a stream using `putObject()` and providing metadata will fail with error:
```
(node:15496) UnhandledPromiseRejectionWarning: S3Error: Metadata cannot be specified in this context.
at Object.parseError (/app/node_modules/minio/dist/main/xml-parsers.js:79:11)
at /app/node_modules/minio/dist/main/transformers.js:156:22
at DestroyableTransform._flush (/app/node_modules/minio/dist/main/transformers.js:80:10)
at DestroyableTransform.prefinish (/app/node_modules/readable-stream/lib/_stream_transform.js:129:10)
at DestroyableTransform.emit (events.js:315:20)
at prefinish (/app/node_modules/readable-stream/lib/_stream_writable.js:611:14)
at finishMaybe (/app/node_modules/readable-stream/lib/_stream_writable.js:620:5)
at endWritable …
```
=> Fix multipart upload from stream with metadata

package.json, src/main/helpers.js, src/main/minio.js, src/test/functional/functional-tests.js
Fix issues with browser environment
Fixes #954
How to test:
Clone and run : https://github.com/prakashsvmx/minio-js-web-browser-example
`npm install`
`npm start` 
Create bucket, upload objects and remove All 
Note the error
Testing the fix:
Checkout this branch and run the below commands
`npm install`
`npm run lint`
`npm run browserify`
`npm run test` - **Optional** since it runs unit test and functional tests
run `npm link` on the root folder  **this is important**
Clone  : https://github.com/prakashsvmx/minio-js-web-browser-example
`npm install`
`npm link minio`  - **this is important to get this fix into this repo for local testing**
`npm start`
=> Fix issues with browser environment

src/test/functional/functional-tests.js
Install `minio` package globally (npm install -g minio) and swap the imports to test locally 
<summary> Local test code </summary>
<details>
replace Line numbers 32-37  with the following because during development the import should be from within package.
```
let helpers
try{
helpers = require('minio/dist/main/helpers')
}catch (err){
helpers=  require("../../../dist/main/helpers")
}
```
</details>
=> fix mint tests import failure for helpers

src/test/functional/functional-tests.js
Mint:  Test file name ( object name) fix . 
```
(1/1) Running minio-js tests ... FAILED in 0 seconds
Error: ENOENT: no such file or directory, open '/mint/data/datafile-versioned-100-kB'
at Object.openSync (fs.js:497:3)
at Object.readFileSync (fs.js:393:35)
```
=> Mint Test file name to object name fix

package.json, src/main/helpers.js, src/main/minio.js
Fixes #964
- Fix broken md5 calculation for tagging requests (S3)
Tested against:
=> Fix request md5 for tagging

src/main/minio.js
Fixes #985
With this fix the copyObject method can be used as explained in the examples
=> Fix copy object request

.eslintrc.js, .gitignore, gulpfile.js, package-lock.json, package.json, src/main/AssumeRoleProvider.js, src/main/CredentialProvider.js, src/main/Credentials.js, src/main/helpers.js, src/main/minio.js, src/main/signing.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js
Assume Role API support
Fixes #841 
Fixes #928
Fixes #818
Start the server
Create user (assign no policy) - Test Error scenarios
Assign policies to test the other scenarios.
Tested with 
<summary> Test Script </summary>
<details>
```
const Arp =  require('../../dist/main/AssumeRoleProvider')
var Minio = require("../../dist/main/minio")
const _ = require('lodash')
const AssumeRoleProvider = Arp.AssumeRoleProvider
// Instantiate the minio client with the endpoint
// and access keys as shown below.
//Play instance
endPoint: 'play.min.io',
port: 9000,
useSSL: true,
accessKey: 'Q3AM3UQ867SPQQA43P2F',
secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
})
//Local testing
minioClient = new Minio.Client({
port: 9000,
useSSL: false, …
```
=> Assume Role API support

.github/workflows/nodejs-windows.yml, .github/workflows/nodejs.yml, package.json
This  PR updates max required version to be node 18 as there is an incompatibility with Node 17.3.1 & Node 16.14.0
=> Updated maximum node version to 18

src/main/minio.js
Fix composeObject error for aws non-versioned bucket
Tested with S3
Closes #1026 
S3 Error in case of un versioned bucket and no versionId is passed.
```
ERROR BODY:
{
"code": "UnknownError",
"amzRequestid": null,
"amzId2": null,
"amzBucketRegion": null
}
REQUEST: HEAD /_100-mb-file-to-test-compose.sf-part2?versionId=
```
=> Fix composeObject error for aws non-versioned bucket

src/main/minio.js
In some error cases, the async `cb` function is called multiple(2) times in `fPutObject`.
https://github.com/minio/minio-js/blob/06e408198fb9000406cc5b2facb50a3276f81df1/src/main/minio.js#L1023-L1033
This causes the `async` library to generate an exception `Error: Callback was already called.`, crashing the process.
This PR is to fix this issue.
=> fix: async callback run multiple times in fPutObject

src/main/minio.js, src/test/functional/functional-tests.js
Hi!,
Adding a missing feature for the post policy. The use case for this is when you want to restrict the mime type by prefix. For example, `image/` should allow any image, either be `image/png` or `image/jpeg` etc
Its also missing an update in `@types/minio` if this PR goes forward.
<https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html>
> Content-Types values for a starts-with condition that include commas are interpreted as lists. Each value in the list must meet the condition for the whole condition to pass. For example,given the following condition:
>
>["starts-with", "$Content-Type", "image/"]
>The following value would pass the condition:
>
>"image/jpg,image/png,image/gif"
=> feature: add content type prefix to post policy

docs/API.md, examples/set-bucket-notification.js, src/main/minio.js
Hi :)
- parameter name should be `bucketName`
- At the example code, `set-bucket-notification.js`, accountID parameter needs to be string(`'1'`). Of course that code will work with JS, but I think this needs to be changed. (Also, at `@types/minio`, accountID type is defined as string.)
=> [docs] Fix parameter name to `bucketName`, Fix example code parameter type

examples/compose-object-test-example.js, src/main/helpers.js, src/test/functional/functional-tests.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> refactor: replace deprecated String.prototype.substr()

src/main/minio.js
fix control flow to return to avoid multiple callbacks by async
s3 gateway test run logs:
```
Gateway Server:
MINIO_ROOT_USER=<> MINIO_ROOT_PASSWORD=<> minio gateway s3 --address ":22000" --console-address ":22001"
```
[gw_test_run.txt](https://github.com/minio/minio-js/files/9429989/gw_test_run.txt)
MinIO Server 
```
MINIO_CI_CD=on MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=minio123 MINIO_KMS_SECRET_KEY=my-minio-key:OSMM+vkKUTCvQs9YL/CVMIMt43HFhkUpqJxTmGl6rYw= MINIO_ ./minio server ~/tmp/D22/d{1...4} --address ":22000" --console-address ":22001"
```
[minio_server_test-run_logs.txt](https://github.com/minio/minio-js/files/9430008/minio_server_test-run_logs.txt)
=> return to avoid multiple callbacks by async

docs/API.md
A missing line break between a table and header in the API.md file caused a formatting issue when publishing to the doc site.
=> Missing line break causing table formatting error

examples/remove-object.js, src/main/minio.js, src/test/functional/functional-tests.js
force delete prefix and object support
=> force delete prefix and object support

.github/workflows/nodejs-windows.yml, .github/workflows/nodejs.yml, package.json
Node19 was released some weeks ago [nodejs](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V19.md#19.0.0). It would be great to be able to use minio-js on devices with the latest release of node.
=> Update node version to node19

src/main/minio.js, src/main/transformers.js, src/main/xml-parsers.js, src/test/functional/functional-tests.js
Fixes #1110
Test script
The remove objects api returns 200 but response with deletion fail reasons for each object
-  A user with readonly policy can be used to simulate this 
```javascript
var s3Client = new Minio.Client({
accessKey: 'test-user',
useSSL:false,
port:22000
})
const deleteList = [
{ name: '1.png'},
{ name: '1.png', versionId:"test-v-is"}
]
s3Client.removeObjects("test-bucket", deleteList ,(e, res) => {
console.log("Multiple objects delete .", res)
})
```
=> improve removeObjects api response handling

src/main/minio.js
When throwing error from presignedPutPbject, string interpolation is disabled and representation of user input is unavailable.
So, I fixed it to enable string interpolation.
=> Fix string interpolation of presignedPutObject

package-lock.json, src/main/minio.js
fix: `removeObjects`  does not delete more than 1000 objects.
test data setup. generate n number of objects for testing batched deletion from js sdk.
```
mc mb local22/test-bucket
mc admin user add  local22 test-user minio123
mc admin policy attach local22 readonly --user test-user  # Access denied for this user for deletion
for ((i = 0 ; i < 1110 ; i++)); do
echo "1" | mc pipe local22/test-bucket/${i}.txt
done
```
now try to delete from the sdk
```
const deleteList = [{name:"non-existent"}]
for(let i=0;i<1110; i++){
deleteList.push({
name:`${i}.txt`
})
}
deleteList.splice(2, 0, { name:"does not exist object2"} )
deleteList.splice(1108, 0, { name:"does not exist object1110"} )
s3Client.removeObjects("test-bucket", deleteList ,(e, res) => {
if (e) {
return console.log(e)
} …
```
=> fix batch deletion in removeObjects

src/main/minio.js
When using the fPutObject() function, in case of an error, the file opened for reading is not closed.
**How to reproduce**
1. Make a test file /tmp/test
```sh
touch /tmp/test
```
2. Create test.js
```js
const Minio = require('minio')
const client = new Minio.Client({
useSSL: false,
endPoint: '127.0.0.1',
port: 9000,
accessKey: 'minioadmin',
secretKey: 'minioadmin'
})
setInterval(() => {
client.fPutObject('test', 'test', '/tmp/test')
.then(() => console.log('ok'))
.catch(err => console.log(err))
}, 1000)
```
3. Run test.js
```sh
node test.js
```
4. Check open files for the process
```sh
lsof -p $(pgrep node)
...
node    52282 user   94r      REG                9,0        0 47450575 /tmp/test
node    52282 user   95r      REG                9,0        0 47450575 /tmp/test
node    52282 user …
```
=> Fixed issue with closing files in fPutObject() function

src/internal/client.ts
s3 doesn't always return bucket region, need to fallback to default region.
This bug is added by https://github.com/minio/minio-js/pull/1156
=> fix: s3 region undefined

build.mjs, package.json, tsconfig.json
close https://github.com/minio/minio-js/issues/1166
This PR doesn't affect any other PR, can be merged separately.
Also no need to run e2e tests, it only change build script, make it rewrite import path in `.d.ts` files
=> fix: cjs type definition

src/xml-parsers.js
fix listIncompleteUploads method returning error uploadIdMarker should be of type string
When there are more than 1000 incomplete uploads with S3, it should successfully list all of them. 
This is not applicable in MinIO
=> fix listIncompleteUploads method returning error uploadIdMarker should be of type string

docs/API.md, examples/list-buckets.js, examples/list-buckets.mjs, src/internal/client.ts, src/internal/xml-parser.ts, src/minio.d.ts, src/minio.js, src/transformers.js, src/xml-parsers.js
refactor `listBuckets` to typescript
=> refactor `listBuckets`

README.md, docs/API.md, examples/remove-bucket-replication.mjs, src/internal/client.ts, src/minio.d.ts, src/minio.js, tests/unit/test.js
"refactor `removeBucketReplication` api to ts" 
Try to remove the bucket replication 
```js
try {
await s3Client.removeBucketReplication('source-bucket')
console.log('Success')
} catch (e) {
return console.log(e)
}
```
<details>
<summary> Steps to setting up a bucket replication </summary>
```
Site 1 (local22)
---------
CI=true  MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=minio123 minio server /tmp/sem{1...4}  --address ":22000" --console-address ":9025"
Site 2(local23)
---------------------------
CI=true  MINIO_ROOT_USER=minio MINIO_ROOT_PASSWORD=minio123 minio server /tmp/semc{1...4}  --address ":23000" --console-address ":9035"
mc mb local22/source-bucket
mc mb local23/dest-bucket
mc version enable local22/source-bucket
mc version enable local23/dest-bucket
mc replicate add …
```
=>  refactor `removeBucketReplication` api to ts

src/internal/type.ts
There are some missing properties in the BucketItem type Union, this PR adds them so TS can detect the correct elements returned by this type differentiating between prefix struct & name/etag struct.
=> Added missing properties for BucketItem union type

README.md
The repo containing the shopping app sample code was archived several years ago, it isn't useful as an example anymore.
=> Remove link to outdated sample code

src/internal/client.ts, src/internal/xml-parser.ts, src/minio.js, src/object-uploader.js
also refactor API to use async/await 
testing script:
```js
import * as minio from 'minio'
async function main() {
const c = new minio.Client({...})
await c.initiateNewMultipartUpload('test', 'oo', {})
const uploadID = await c.findUploadId("test", 'oo')
console.log(uploadID)
}
main().catch(e => {
throw e
})
```
=> refactor findUploadId to TypeScript

src/internal/client.ts, src/internal/join-host-port.ts, tests/unit/test.js
=> fix: enclose ipv6 host with brackets on client request

src/xml-parsers.js
Fix handling with Amazon S3 where the ListObjects request is truncated, but "NextMarker" is not returned, as decribed in https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html#AmazonS3-ListObjects-response-NextMarker
=> Fix truncated ListObjects request handling with non-existing NextMarker

src/minio.d.ts
this class has been moved to notification.ts
=> remove TargetConfig from minio.d.ts

package-lock.json, package.json
Hey! We've spent some effort lately to clean up the buffer-crc32 library and push the 1.0.0 release forward. Thought you may want to upgrade! Should be a drop-in replacement, as you don't support very old Node.js versions already.
=> Update buffer-crc32 to 1.0.0

src/internal/helper.ts
uriEscape to comply with s3.
S3 percent-encodes some extra non-standard characters in a URI . So comply with S3. 
```javascript
//get stream
try {
//const result = await s3Client.putObject('test-bucket', `/sa-test-ba/KYC/楽天モバイル法人契約端末購入証明書_[21213213]_[20231113]_[BCDE ddnsf3 litelite 手帳型ケース シンプル ネイビー2])].pdf`,fileStream, stat.size )
const result = await s3Client.putObject('test-bucket', `rfc3986/rfc3986-filename_test (123)äöü 🥳.txt`,fileStream, stat.size )
} catch (err) {
console.log("Error putObject ",  err.message, )
}
const getPresignedUrl = async function(){
const getUrl = await s3Client.presignedGetObject("test-bucket", `rfc3986/rfc3986-filename_test (123)äöü 🥳.txt`)
console.log(getUrl)
}
getPresignedUrl()
```
=> uri escape to comply with s3

package-lock.json, src/internal/client.ts
when listing buckets use the configured or default region
We fetch the region automatically only for buckets.  so for `listBuckets`, either a region is required or use the default.
The latest version/master `listBuckets` does nor return any result .  setting a default region would work as part of the client config. 
```js
var mc = new Minio.Client({
useSSL: false,
//partSize: 1024 * 1024 * 5,
port: 22000,
region:"us-east-1"
})
```
=> fix: regression when listing buckets use the configured or default region

README.md, docs/API.md, examples/get-object-retention.mjs, examples/put-object-retention.mjs, package-lock.json, src/internal/client.ts, src/internal/type.ts, src/internal/xml-parser.ts, src/minio.d.ts, src/minio.js, src/transformers.js, src/xml-parsers.js, tests/unit/test.js
refactor getObjectRetention to ts
=> refactor `getObjectRetention` to ts

docs/API.md, examples/remove-objects.js, src/internal/client.ts, src/internal/type.ts, src/internal/xml-parser.ts, src/minio.d.ts, src/minio.js, src/transformers.js, tests/unit/test.js
refactor `removeObjects` api to ts
testing with 1000+ entries from the caller should be successful  more testing info from https://github.com/minio/minio-js/pull/1131
=> refactor `removeObjects` api to ts

README.md, README_zh_CN.md, examples/make-bucket.mjs, src/internal/client.ts
fix use configured region from constructor for makebucket
Fixes https://github.com/minio/minio-js/issues/1292
```
const s3Client = new Minio.Client({
useSSL: false,
port: 22000,
// region:'us-west-1'
//partSize: 5 * 1024 * 1024,
})
// Create a bucket name my-bucketname-3.
// await s3Client.makeBucket('my-bucketname-3')
// Create a bucket name my-bucketname.
// await s3Client.makeBucket('my-bucketname-2','us-west-1')
// List all object paths in bucket my-bucketname-2. and observe trace for the correct region in request. 
var objectsStream = s3Client.listObjects('my-bucketname-2', '', true)
objectsStream.on('data', function (obj) {
console.log(obj)
})
objectsStream.on('error', function (e) {
console.log(e)
})
```
to change …
=> fix use configured region from constructor for makebucket

src/internal/client.ts, tests/unit/test.js
Resolves #1312 
Additionally, remove unnecessary `isFunction` checks as that is now handled by the callbackify wrapper.
Added module in unit test library for better coverage.
=> Ensure default expiration parameter is set for presigned URLs

package-lock.json, package.json
Even though this PR was merged https://github.com/minio/minio-js/pull/1328
`npm` pulls `"fast-xml-parser": "^4.2.2"` from `package.json`
Which has `Regular Expression Denial of Service (ReDoS)` https://security.snyk.io/package/npm/fast-xml-parser
=> fix: fast-xml-parser version

src/internal/client.ts
The type import of `PostPolicyResult` in `src/internal/client.ts` is missing its file extension. 
This can cause issues with projects requiring file extensions on import paths:
```
node_modules/minio/dist/esm/internal/client.d.mts:11:39 - error TS2307: Cannot find module '../minio' or its corresponding type declarations.
11 import type { PostPolicyResult } from '../minio';
~~~~~~~~~~
Found 1 error in node_modules/minio/dist/esm/internal/client.d.mts:11
``` 
I've added a `.ts` file extension similar to the import of `xml-parser.ts`, which also only exists as `.js`-file
=> fix: add missing file extension to import

src/internal/client.ts
I had an issue where this minio client throws a `InvalidArgumentError: Unable to get bucket region for ...` error when trying to retrieve a presigned url. I was so confused as to why would I need to configure bucket regions for minio because I'm running it locally on as a docker container.
I modified the source to `console.error` the error and it appears like the original error was actually an `ECONNREFUSED`, masked behind the incorrect `InvalidArgumentError` because of the large try-catch statement.
In this PR, I made it so that it would only throw `InvalidArgumentError` only when the originating error is an `InvalidBucketNameError`, and rethrow any other error.
=> Rethrow exceptions other than InvalidBucketNameError

src/internal/type.ts, src/internal/xml-parser.ts, tests/functional/functional-tests.js
split the UserTags from xml to object.
=> added tags response from listObjectsV2WithMetadata

src/internal/client.ts
S3 API can upload a binary file in the body. We need this feature for users to implement slicing and uploading files themselves.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html
=> fix: uploadPart cannot upload stream and etag error

src/internal/helper.ts
I want the port to support string type for two reasons:
1. Many well-known libraries support both string and number for port configuration, since ports are typically loaded from env files where values are strings. This way, users don't need to perform type conversion.
2. Many people, including myself, find that when the port is passed as a string type, the error message is not very clear, only showing "invalid port".
=> feat: port support string type

src/internal/helper.ts
S3 and the Minio server both support [conditional writes](https://blog.min.io/leading-the-way-minios-conditional-write-feature-for-modern-data-workloads/) using `If-None-Match` and `If-Match`. Fwiw, this is [already supported](https://github.com/minio/minio-go/blob/ffa2ddd6f2b41e522235a3c61fb4ff5910a842d7/api-put-object.go#L132) in the Go client.
Previously this was treating those parameters as metadata, but now they're treated as proper headers.
Example:
```
minioClient.putObject(
"my-bucket",
"my-object",
"object-content",
undefined,
{
"If-None-Match": "*",
}
);
```
=> Support if-none-match and if-match headers.

src/IamAwsProvider.ts, src/internal/client.ts
Allow to authenticate against AWS S3 using IRSA (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
=> feat: add iam aws provider

package-lock.json, src/internal/client.ts
fix optional params typing in few apis
Fixes #1247
=> fix optional params typing in few apis

.github/workflows/lint.yml, .github/workflows/test.yml
Add Node.js 22 to CI version matrix. It is the current LTS version of Node, so makes sense to ensure the JS client works with that too.
For successful test run, see the PR in this [fork](https://github.com/stscoundrel/minio-js/pull/1)
=> CI: add Node 22 to version matrix

package-lock.json, src/internal/client.ts
fix 0 byte file upload
Fixes https://github.com/minio/minio-js/issues/1386
Test Script:
<details>
```js
import * as Minio from 'minio'
import * as fs from 'fs'
import * as stream from 'stream'
port: 22000,
useSSL: false,
//pathStyle:true
})
const testUserBug = async () => {
const destinationObject = 'empty-file'
var metaData = {
'Content-Type': 'text/plain',
'X-Amz-Meta-Testing': 1234,
example: 5678,
}
const filePath = '/dev/null'
const stream = fs.createReadStream(filePath, { highWaterMark: 1024 * 1024 })
//const { size } = await fs.promises.stat(filePath)
// const result = await minioClient.putObject('test-bucket', destinationObject, stream, metaData)
//console.log(result)
let size = 0 …
```
=> fix 0 byte file upload

src/internal/client.ts
Hello all,
previously, putOpts was required, causing issues when not provided.
This fix makes it optional as intended.
Also the `examples/set-object-tagging.mjs` is now working as intended.
Resolves #1247
=> Fix: make putOpts optional in setObjectTagging

src/internal/client.ts, src/internal/request.ts, src/internal/xml-parser.ts, tests/unit/test.js
add retry for http retryable requests
e.g:
```js
import * as fs from 'node:fs'
import * as Minio from 'minio'
import * as stream from 'stream'
port: 22000,
useSSL: false,
region: 'us-west-1',
//pathStyle:true
})
const retryTest = async () => {
try {
const filePath = '/home/prakash/Downloads/test-all-file-types/Sizes/1GB.zip'
const stream = fs.createReadStream(filePath, { highWaterMark: 1024 * 1024 })
const { size } = await fs.promises.stat(filePath)
const result = await minioClient.putObject('test-bucket', '1GB.zip', stream, size)
console.log('Upload success ', result)
} catch (err) {
console.log('Error in caller:', err.message)
}
}
retryTest()
```
```sh
chmod 000 ./data{1..3}/
or revert …
```
=> add retry for http retryable requests

src/internal/request.ts, tests/functional/functional-tests.js, tests/unit/test.js
Verified with `q` 
```
Cloning minio-js.git
Fetching origin
Branch 'fix-bug-error-rethrow' set up to track remote branch 'fix-bug-error-rethrow' from 'origin'.
Switched to a new branch 'fix-bug-error-rethrow'
Commit version 8.0.5
Building for release
Verifying build
Node version: v20.18.3  
Publishing release 8.0.5
Tagging release 8.0.5
Successfully released 8.0.5
Announce this release by adding release notes at
https://github.com/minio/minio-js/releases from 'trusted@minio.io'
account.  Release notes requires two sections 'highlights' and
'changelog'.
Highlights is a bulleted list of salient features in this
release and Changelog contains list of all commits since the last
release by;
git log --no-color --date=format:'%m/%d/%y' --pretty=format:'- %s (%ad) <%an>' 8.0.4..8.0.5
```
=> fix bug in retry while error handling

src/internal/client.ts, tests/functional/functional-tests.js
- update `fPutObject` to use `stat` instead of `lstat`
- update functional test to include 0byte file
- fix upload of files larger than 1GB as `stream.readableLength` is not compatible
- 
Fixes https://github.com/minio/minio-js/issues/1395
=> fix large object upload and and update functional test for 0 byte file upload

.github/workflows/test.yml, src/internal/extensions.ts, src/internal/type.ts
=> test with node v24

src/transformers.js
currently parser error like:
https://github.com/minio/minio-js/blob/8.0.5/src/xml-parsers.js#L101 will be un-catchable from app code
to reproduce similar situation, change local code in `parseListObjectsV2` in `node_modules/minio/dist/main/xml-parsers.js` to:
```diff
-- if (!xmlobj.ListBucketResult) {
throw new errors.InvalidXMLError('Missing tag: "ListBucketResult"');
-- }
```
and try catch this error from `mc.listObjectsV2()`
=> Fix: redirect xml parser error to stream error, else error is uncatchable 
