- src/main/minio.js
> Revert "Add acl query string for setBucketACL()"

- README.md
- examples/presigned-postobject.js
- src/main/minio.js
- src/main/signing.js
Original author has hardcoded "Scope" everywhere in signing.js I will send a separate fix making it as a function.
> Implement presigned POST requests

- .travis.yml
- appveyor.yml
- examples/list-buckets.html
- gulpfile.js
- package.json
- src/main/list-objects.js
- src/main/minio.js
- src/main/multipart.js
- src/main/signing.js
- src/main/simple-requests.js
- src/main/upload.js
- src/test/unit/test.js
Fix a bug where protocol was null for http based requests.
> Add browserify and build isomorphic library - fixes #309

- API.md
- README.md
- src/main/minio.js
- src/test/unit/test.js
> putObject: put object read stream should precede size.

- API.md
- src/main/minio.js
- src/test/unit/test.js
> makeBucket: Should take region as last argument.

- examples/fget-object.js
- examples/fput-object.js
- package.json
- src/main/helpers.js
- src/main/minio.js
- src/main/multipart.js
- src/main/signing.js
- src/main/transformers.js
Not ready to merge, please review the logic. Pending items - show examples for fGetObject and fPutObject. Add comments. Fix the FIXME introduced
> fPutObject and fGetObject

- src/main/minio.js
- src/main/signing.js
Also use all the unused error responses.
> getBucketLocation: Simplify getBucketLocation handling and improve overall message.

- src/main/minio.js
- src/main/transformers.js
> Fix resource leaks - registered callbacks should be called, response stream should be read.

- API.md
- src/main/minio.js
- src/main/signing.js
- src/test/functional/functional-tests.js
> PresignedGet: Support for overriding response headers.

- src/main/minio.js
> statObject: ETag is optional handle it.

- README.md
Added API Reference Section.
Added individual links to each API.
Brought it as close as possible to docs site.
Add constructor so that this document is complete in itself.
Removed How to Run this example section.
Changed desc to description in the table heading.
Call it Full Docs Site to Complete Documentation.
> docs: README.md updated to be in sync with docs.minio.io

- API.md
doc: API.md/updated to match with docs.minio.io
> doc: API.md/updated to match with docs.minio.io

- API.md
Testing changes so that code blocks and headings are separated by a line.
> docs: Test changes so that code block render correctly on Doctor.

- docs/API.md
The anchor was closed. Made API names headings prominent. Fixes : https://github.com/minio/cookbook/issues/31
> bugfix: Anchor tag needed to be closed.

- docs/API.md
Missed bucketExists anchor fix.
> doc: Anchor fixes

- docs/API.md
> Doc: document the error information for bucketExists() call.

- src/main/minio.js
- src/main/transformers.js
> Disable sha256 calculation and use UNSIGNED-PAYLOAD for sha256 header for signature calculation.

- src/main/helpers.js
Custom percent encoding implementated as encodeURIComponent() was not encoding certain characers like "("
> Implement custom percent encoding function.

- docs/API.md
- examples/bucket-exists.js
- examples/delete-bucket-notification.js
- examples/fget-object.js
- examples/fput-object.js
- examples/get-bucket-notification.js
- examples/get-object.html
- examples/get-object.js
- examples/get-partialobject.js
- examples/list-buckets.js
- examples/list-incomplete-uploads.js
- examples/list-objects.js
- examples/make-bucket.js
- examples/presigned-getobject.js
- examples/presigned-postpolicy.js
- examples/presigned-putobject.js
- examples/put-object.js
- examples/remove-bucket.js
- examples/remove-incomplete-upload.js
- examples/remove-object.js
- examples/set-bucket-notification.js
- examples/stat-object.js
- src/main/minio.js
- src/main/notification.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/unit/test.js
Still some few changes needed before merging, do not review
> Get/Set/Delete Notification Config

- docs/API.md
- examples/list-objects-v2.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
> Add ListObjects V2 API

- README.md
- docs/API.md
> doc: update doc regarding the API change "new Minio()" to "new Minio.Client()"

- docs/API.md
- examples/minio/listen-bucket-notification.js
- src/main/minio.js
- src/main/notification.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
API is changed to take 'prefix, suffix and events' as parameters.
> api: ListenBucketNotification api change to reflect the changes on server

- README.md
> Add doc/ref examples for bucket policy/notification, listObjectV2, removeIncompleteUpload

- docs/API.md
- src/main/s3-endpoints.js
This should fix #489 
#hacktoberfest
> Add support for cn-north-1 endpoint (#489)

- README.md
- docs/API.md
- examples/copy-object.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
Comments and documentation are missing until we agree on the copy object API.
@krishnasrinivas, can you review this PR ?
> Add CopyObject API

- examples/fput-object.js
- package.json
- src/main/helpers.js
- src/main/minio.js
- src/main/object-uploader.js
- src/test/unit/test.js
> Fix contentType set properly with putObject, fPutObject.

- README.md
- docs/API.md
Resending with both files updated with slack badges.
> slackupdates : Change of badge from gitter to slack

- src/main/transformers.js
> Handle non-XML errors from the proxy.

- src/main/minio.js
> Make endPoint case insensitive.

- src/main/object-uploader.js
> api: Use createHash instead of new Hash()

- src/main/minio.js
Remove dummyTransformer reference.
> api: Dummy stream reader no longer exists.

- src/main/minio.js
> build: Do not import non existent functions.

- src/main/minio.js
> build: Import missing isDate properly

- package.json
- src/main/minio.js
Add command in package.json for browserify.
Fixes #572
> Remove bind() for arrow functions.

- src/test/functional/functional-tests.js
- Added copy objects with conditions, remove object and stat custom content-type to existing tests
- use data files from /mint/data
> fix functional tests to work with mint

- src/test/functional/functional-tests.js
- src/test/unit/test.js
We had decided to remove all the mock tests.
> Remove mock unit tests as we have functional tests now

- src/test/functional/functional-tests.js
Removing putobject string buffer test as it is incorrect.
There are chances that some unicode character can come into
play and the test might occasionally fail.
Fixed a Hash calculation bug in getpartialobject test, seen in Mint.
The code assumed that the first 100KB of data in the 6MB object will
have the same size as a 100KB object itself.
The listobjects test to list 1001 objects fails intermittently in removeObject part of the test
in Appveyor. Created issue https://github.com/minio/minio-js/issues/629 for tracking purpose.
Fixes #627 and #629
> Fix Hashing bug and remove putobject string and list 1001 objects tests

- src/test/functional/functional-tests.js
tests that call listenBucketNotification handles "Not Implemented"
error code.
Fixes #636
> Ignore Not Implemented error code in functional test

- .gitignore
- docs/API.md
- package.json
- src/main/minio.js
- src/test/functional/functional-tests.js
> Generates generic presigned url for a HTTP method

- src/test/functional/functional-tests.js
Add 'NotImplemented' error handlers,
Add wait time before recreating a bucket in Azure,
> Modify functional tests to run on Gateway

- src/test/functional/functional-tests.js
Log the arguments passed to the java script SDK API calls
to be helpful in Mint.
> Log arguments passed to the Java script SDK API calls

- docs/API.md
- docs/zh_CN/API.md
- examples/presigned-postpolicy.js
- package.json
- src/main/minio.js
- src/test/functional/functional-tests.js
Consolidate callback params to support promise
Fixes #653
> Consolidate callback params in presignedPostPolicy

- src/main/helpers.js
- src/test/unit/test.js
This is done to support all Amazon endpoints.
> Remove IsAmazonEndpoint check in IsValidEndpoint

- src/main/signing.js
> Small typo

- README.md
I wrote [typings]( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23647). Now it may be installed via `npm install --save-dev @types/minio`.
> Add typings installation

- docs/API.md
I've read the code and the docs and found a few inaccuracies.
Am I right?
> Correct documentation

- docs/API.md
- src/main/minio.js
> Make region optional in makebucket API

- docs/API.md
- src/main/minio.js
- Some errors in the code comments have been corrected for the
properties of return values on some functions.
- The documentation has been updated for statObject with the new return
value.
Fixes #673
> Change type of lastModified to Date for return value of statObject

- src/test/functional/functional-tests.js
Azure gateway accepts only "download" policy
> Fix bucket-policy functional test for Azure

- docs/API.md
- examples/remove-objects.js
- package.json
- src/main/minio.js
- src/test/functional/functional-tests.js
Function **removeObjects(bucketName, objectsCh)**
objectsCh - Channel of objects to be removed ( used [this](https://github.com/NodeGuy/channel) for channels )
Behaves exactly like go sdk's [removeObjects](https://github.com/minio/minio-go/blob/master/docs/API.md#RemoveObjects) , returns a stream of errors 
Fixes: #695
> removeObjects API - Removes all the objects residing under a bucket (API)

- .npmignore
- package.json
Can just do npm install from link, and the dist folder will build, should be good.
> adding urllink support

- src/main/minio.js
Added promisify for removeObjects. see #704 
Hope this helps.
> promisified removeObjects

- src/main/minio.js
fixes #708 
@kmkanagaraj can you review if this is the right thing to do?
> Remove source-map-support in the source

- package.json
Fixes vulnerability issue. Superagent is updated to v3.7.0, vulnerability is fixed in this version.
> Updated superagent dependency to v3.7.0.

- README.md
- README_zh_CN.md
> fix wrong fPutObject example in README

- src/main/minio.js
Fixes https://github.com/minio/minio-js/issues/743
> Removed metadata from PutObjectPart calls

- src/main/minio.js
This PR implements the fix suggested in PR #732
Fixes #730
> Add missing promisify entry for presignedUrl

- docs/API.md
> Fix broken link to bucket policy

- src/main/minio.js
- src/test/functional/functional-tests.js
This commit fixes the use of async.whilst function as well as multipart
not being covered in the functional tests after the part size was
changed from 5MB to 64MB and the only test that checked this was
subsequently removed.
Fixes #788
> Fix multipart fPutObject

- docs/API.md
- src/main/minio.js
> Add ability to set family as a request option

- docs/API.md
Also, remove the statement about resume upload.
> Doc: Change default part size to 64MiB

- src/main/minio.js
- src/main/signing.js
PR #622 was incomplete, this PR completes
sessionToken support
Fixes #829
> fix STS token support for presign/postsign

- src/main/minio.js
- src/main/signing.js
PR #830 was incomplete, this PR completes
sessionToken support
Fixes #829
> fix STS token support for presign

- src/main/minio.js
- src/test/functional/functional-tests.js
> fix: correctly set content-length size when payload has unicode

- docs/API.md
- examples/remove-object.js
- examples/stat-object.js
- src/main/helpers.js
- src/main/minio.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
VersionId support for removeObject and statObject API
> VersionId support for removeObject and statObject API

- docs/API.md
- examples/fget-object.js
- examples/get-object.js
- examples/get-partialobject.js
- src/main/helpers.js
- src/main/minio.js
- src/main/object-uploader.js
- src/test/functional/functional-tests.js
VersionId support in get,put object APIs and respective response
> VersionId support in get,put object APIs

- docs/API.md
- examples/presigned-getobject-request-date.js
- src/main/minio.js
- src/test/functional/functional-tests.js
VersionId support in pre signed url ( get)
> versionId support in presigned url

- README.md
- docs/API.md
- examples/get-bucket-lifecycle.js
- examples/remove-bucket-lifecycle.js
- examples/set-bucket-lifecycle.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
Set and Get Bucket Life cycle support
`setBucketLifecycle(bucketName, lifecycleConfig, cb)`
`removeBucketLifecycle(bucketName, cb)` - Remove lifecycle configuration
`getBucketLifecycle(bucketName, cb)`
Closes #831
> Set and Get and remove Bucket Life cycle config support

- docs/API.md
- examples/get-bucket-encryption.js
- examples/remove-bucket-encryption.js
- examples/set-bucket-encryption.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
The following Bucket Encryption APIs are implemented:
`setBucketEncryption(bucketName, encryptionConfig, cb)`
`getBucketEncryption(bucketName, cb)`
`removeBucketEncryption(bucketName, cb)`
Tested against:
Test setup pointing to KMS: ( Certificates should have been placed, update mc to latest version)
```
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373;export MINIO_KMS_KES_KEY_FILE=root.key;export MINIO_KMS_KES_CERT_FILE=root.cert;export MINIO_KMS_KES_KEY_NAME=my-minio-key; 
MINIO_ROOT_USER=<minio> MINIO_ROOT_PASSWORD=<minio123> ./minio server /tmp/mt{1...4}
```
<summary>Test script attached:</summary>
<details>
var Minio = require("../../dist/main/minio") …
> Bucket Encryption APIs get/set/remove

- README.md
- docs/API.md
- examples/set-accelerate-end-point.js
- src/main/minio.js
Amazon S3 Transfer Acceleration endPoint support
`setS3TransferAccelerate(endPoint)`
> setS3TransferAccelerate option support for s3 only

- .github/workflows/nodejs.yml
and build CI/CD only with LTS versions
> remove EOLed node versions

- package.json
Upgrade lodash version
Fixes #936
> Upgrade lodash version

- src/main/notification.js
Fixes #918
Replication steps as in the linked ticket.
> Pass default region to fix user bucket notification bug

- .eslintrc.js
- src/main/extensions.js
- src/main/helpers.js
- src/main/minio.js
- src/main/notification.js
- src/main/object-uploader.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
- update eslint rules for comments
- fix comment format
> do not ignore errors in tests

- src/main/extensions.js
- src/main/helpers.js
- src/main/minio.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
Decode special characters in object name in list object methods:
`listObjects`
`listObjectsV2`
`extensions.listObjectsV2WithMetadata`
Fixes #943
Tested Against
<summary> Test JS Code  </summary>
<details>
```
var Minio = require("../../dist/main/minio")
const _ = require('lodash')
// Instantiate the minio client with the endpoint
// and access keys as shown below.
//Play instance
endPoint: 'play.min.io',
port: 9000,
useSSL: true,
accessKey: 'Q3AM3UQ867SPQQA43P2F',
secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
})
//Local testing
minioClient = new Minio.Client({
port: 9000,
useSSL: false,
secretKey: 'minio123'
})
const file = '/home/user/Downloads/Temp/MinIOJSTestObjects/example&.pdf'
const bucketName = …
```
> Special characters in object name in list objects

- src/main/helpers.js
> Simplifying isValidEndpoint

- docs/API.md
Because the example can't get the expected answer.
因为我的英文很差,所以中文重复一边,万一你懂中文呢
更新原因, 示例无法返回可以理解的答案.并且在使用中会有没有返回值的情况
> update fn : listObjects;  更新函数  listObjects

- src/main/minio.js
- src/test/functional/functional-tests.js
Fix consistent response in put, multipart calls
Added functional tests for the same.
Fixes: https://github.com/minio/minio-js/issues/990
Tested:
> Fix consistent response in put, multipart calls

- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
Fixes #992 
Fix special character handling for **prefix**
Tested with
> Fix special character handling for prefix in listings

- src/test/functional/functional-tests.js
Refactor versioned presigned url tests
Fixes #988
> Refactor versioned presigned url tests

- .github/workflows/nodejs-windows.yml
- .github/workflows/nodejs.yml
- src/test/functional/functional-tests.js
Run Tests in GitHub CI using actions instead of play.min.io
How to test:
Linux:
I have used https://github.com/nektos/act to run the actions locally and verify the status. 
Windows:
Passing as per the actions
Note:  Modified a functional test to remove windows specific special characters in object name.
> Run Tests in GitHub CI using actions instead of using play instance

- README.md
- docs/API.md
- examples/compose-object-test-example.js
- examples/compose-object.js
- package.json
- src/main/helpers.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
Compose object API Support
`composeObject(destConfig, sourceObjectList, cb)`
Tested with
Fixes #895
> Compose object API Support

- README.md
- docs/API.md
- examples/sel-object-content.js
- examples/select-object-content.js
- package-lock.json
- package.json
- src/main/helpers.js
- src/main/minio.js
- src/main/transformers.js
- src/main/xml-parsers.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
Select Object Content API
`selectObjectContent(bucketName, objectName, selectOpts={}, cb)`
Fixes #846 
Tested with
<summary> Test script <summary>
<details>
```
var Minio = require("../dist/main/minio")
var s3Client = new Minio.Client({
endPoint: 's3.amazonaws.com',
accessKey: 'YOUR-ACCESSKEYID',
secretKey: 'YOUR-SECRETACCESSKEY'
})
const bucketName = "test-bucket"
const objectName="phonebook.csv"
s3Client.putObject(bucketName, objectName,"Name,PhoneNumber,City,Occupation\n" +
"Sam,(949) 123-45567,Irvine,Solutions Architect\n" +
"Vinod,(949) 123-4556,Los Angeles,Solutions Architect\n" +
"Jeff,(949) 123-45567,Seattle,AWS Evangelist\n" +
"Jane,(949) 123-45567,Chicago,Developer\n" +
"Sean,(949) 123-45567,Chicago,Developer\n" +
"Mary,(949) 123-45567,Chicago,Developer\n" +
"Kate,(949) …
```
> Select Object Content API

- .github/workflows/nodejs-windows.yml
- .github/workflows/nodejs.yml
- package.json
Test and upgrade for node-js version 17
> Test and upgrade for node-js version 17

- package-lock.json
- package.json
Fix the node version and update package-lock.json as well
> Fix the node version and update package-lock.json as well

- docs/API.md
- docs/zh_CN/API.md
- examples/presigned-postpolicy.js
- src/main/minio.js
- src/test/functional/functional-tests.js
- src/test/unit/test.js
This PR is to address https://github.com/minio/minio-js/issues/1034
Feel free to do whatever you want with this code sample. The package @types/minio would also need an update.
Test it well since I only spent a couple minutes on it. I might have missed something.
> feature: add user defined metadata and content disposition to post policy

- package-lock.json
- src/main/minio.js
Fix mint test failure in s3 gateway mode
tested with 
- S3 Gateway
- MinIO server
> Fix mint test failure in s3 gateway mode

- README.md
- README_zh_CN.md
- src/test/functional/functional-tests.js
Updates URLs for the docs site with replacements for the new docs.
> Updating documentation links with new URLs

- src/main/helpers.js
> Fix an issue when objectName might be not a type of string

- package-lock.json
- package.json
- src/main/helpers.js
- src/main/xml-parsers.js
> upgrade fast-xml-parser package

- .prettierignore
- README.md
- docs/API.md
prettier support format markdown and js code block in markdown
> chore: format docs/API.md with prettier

- package-lock.json
- package.json
- src/minio.js
npm package [xml](https://www.npmjs.com/package/xml) doesn't have any update for 8 years, use `xml2js` to serialize js object to xml
> remove dependency `xml`

- README.md
- docs/API.md
- examples/get-bucket-encryption.mjs
- examples/remove-bucket-encryption.mjs
- examples/set-bucket-encryption.mjs
- src/internal/client.ts
- src/internal/type.ts
- src/internal/xml-parser.ts
- src/minio.d.ts
- src/minio.js
- src/transformers.js
- src/xml-parsers.js
- tests/unit/test.js
refactor encryption apis to ts
`setBucketEncryption`
`getBucketEncryption`
`removeBucketEncryption`
> refactor encryption apis to ts

- docs/API.md
- examples/remove-incomplete-upload.mjs
- src/internal/client.ts
- src/minio.js
- tests/unit/test.js
migrate `removeIncompleteUpload` api to ts
Note: It is a no-op in MinIO
Can be used/tested with AWS S3.
> migrate `removeIncompleteUpload` api to ts

- docs/API.md
- examples/copy-object.mjs
- src/internal/client.ts
- src/internal/type.ts
- src/internal/xml-parser.ts
- src/minio.d.ts
- src/minio.js
- src/transformers.js
- src/xml-parsers.js
refactor `copyObject` api to ts
> refactor `copyObject` api to ts

- src/internal/client.ts
- src/internal/type.ts
update types for bucket versioning
Closes #1296
> update types for bucket versioning

- src/internal/type.ts
fix lifecycle expiry type fields
only expiry days is mandatory other fields are optional
> fix lifecycle expiry type fields

- README.md
- README_zh_CN.md
- docs/API.md
- examples/presigned-getobject-request-date.mjs
- examples/presigned-getobject.mjs
- examples/presigned-postpolicy.mjs
- examples/presigned-putobject.mjs
- src/helpers.ts
- src/internal/client.ts
- src/internal/type.ts
- src/minio.d.ts
- src/minio.js
- src/signing.ts
- tests/unit/test.js
> refactor presigned apis to ts

- package-lock.json
- package.json
> fix: relax xml2js version constraint

- src/internal/xml-parser.ts
fixes #1340
Sample results. 
```
[
{ name: '0000test-bucket', creationDate: 2024-09-03T09:29:38.112Z },
{
name: '01110000111100001111000011110000',
creationDate: 2024-09-03T08:39:04.766Z
},
{ name: '01test-bucket', creationDate: 2024-09-03T09:29:33.168Z },
{ name: '0test-bucket', creationDate: 2024-09-03T09:29:29.961Z },
{ name: '90test-bucket', creationDate: 2024-09-03T09:29:43.040Z },
{ name: 'test-bucket', creationDate: 2024-09-03T07:11:19.678Z }
]
```
> force xml parser to treat bucket name as string in `listBuckets`  API

- src/internal/client.ts
When receive 403 status code for invoke GetBucketLocation api, make  alignment with mc client 
Related issue: https://github.com/minio/minio-js/issues/1337
> feat: alignment with mc client

- src/internal/client.ts
> fix: skip uploaded part

- src/internal/client.ts
> Fix #1372 - File download with encoded etag

- tests/functional/functional-tests.js
- tests/unit/test.js
increase test timeout to 5 minutes
> increase test timeout to 5 minutes

- src/internal/client.ts
- src/internal/helper.ts
- src/internal/xml-parser.ts
- tests/functional/functional-tests.js
currently it is parsed as a nested array.. make it flat array always
Fixes https://github.com/minio/minio-js/issues/1397
```js
import * as Minio from 'minio'
port: 22000,
useSSL: false,
//pathStyle:true
})
const testTagging = async () => {
//const tags = { test: 'test' }
const tags = { test: 'test', test1: 'test1' }
await minioClient.setObjectTagging('test-bucket', '1.txt', tags)
const tagging = await minioClient.getObjectTagging('test-bucket', '1.txt')
console.dir(tagging)
}
testTagging()
//Result
[ { Key: 'test', Value: 'test' }, { Key: 'test1', Value: 'test1' } ]
```
> fix tag parsing and type and update validation and tests

- src/internal/client.ts
> fix: make `getBucketRegionAsync` public
